### ISSUE TITLE
QA function down-asyncio Issue

### ISSUE THREAD

**Issue by aniketkadam20** [aniketkadam20/ANDLAB#1]
name | about | labels
-- | -- | --
Bug Report | Report a bug while installing asyncio library | kind/bug

**What happened:** QA function app went down when we installed asyncio library 

**What you expected to happen:** Saw few reference of asyncio in the code and it was missing in requiremts,txt file, so we added asyncio==3.4.3 to the file but installing aysncio from pyhton 3.7 caused some issues with these pathches. 

**How to reproduce it (as minimally and precisely as possible):** Currently we don't need asyncio so this library was removed from the dependency file.

**Anything else we need to know?:** To insatll asyncio library from pyhton 3.7

[a link] https://github.com/Azure/azure-functions-python-worker/blob/dev/azure_functions_worker/_thirdparty/aio_compat.py

**Comment by aniketkadam20** [comment]
Asyncio library Issue

**Comment by rgupta319** [comment]
How to reproduce it - This is talking about the solution and not how to reproduce it. Please change that. 

Please add the following sections:
Environmental details on which the issue was identified
Program - Azure Functions with runtime v3
OS - **<Linux with version>**,
Date and time - <**of first occurrence**>
Azure Resource Details (without credentials) 

Cause and Resolution/Workaround -
Mention the issue about the incompatibility of the asyncio version with the Python runtime version
Mention the solution to remove it as it was not needed
