### ISSUE TITLE
Azure DevOps Build Pipeline can't get secrets from Key Vault when secured with vnet and firewall

### ISSUE THREAD

**Issue by aniketkadam20** [aniketkadam20/ANDLAB#2]
name | about | labels
-- | -- | --
Bug Report | Report a bug while reading secrets from Key Vault| kind/bug

**What happened:** Azure DevOps Build Pipeline can't get secrets from Key Vault when secured with vnet and firewall.(Client address is not authorized and caller is not a trusted service)

![image](https://user-images.githubusercontent.com/38543166/85239403-4095a900-b3f9-11ea-9d06-1518f55832a6.png)

**What you expected to happen:**  CosmosDB URI was stored as a secret in Key Vault, Using azure key vault task it was expected to read secret from yaml file.

**How to reproduce it (as minimally and precisely as possible):**  You can add a step in the build definition to whitelist the agent IP address, then remove it from the whitelist at the end of the build. This is not a solution but a workaround

**Anything else we need to know?:**
 https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#agent-ip-ranges

**Comment by rgupta319** [comment]
**How to reproduce it** - This is talking about the solution and not how to reproduce it. Please change that. Whitelisting and etc is the workaround.

Please add the following sections:
**Environmental details on which the issue was identified**
Calling Program - **Azure DevOps pipeline**
OS - **<Provide the agents OS and version being requested>**, 
Self hosted or Microsoft Hosted agents - **<True/False>**
Date and time - **<Provide the date of the issue occurrence>**
Azure Resource name that failed to respond (name of the resource, location of the resource)
VNet - CIDR IP/Range only

**Resolution/Workaround** -
1) Whitelisting during build and blacklisting after build
2) Use the known methodology as per the link https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#agent-ip-ranges
3) Avoid reading these sort of data from Azure DevOps pipeline. Instead read from the actual code that needs the data from the Vault, unless the code being deployed don't have the network access or architecturally is not allowed to.
